plugins:
  - jekyll-remote-theme
remote_theme: zivong/jekyll-theme-hydure
title: Stan Chen
tagline: It's all about creating values with data. 🚀🚀🚀
author.name: Stan Chen
author.url: https://github.com/stancsz